/* ===========================================================================
                           TTB Plugin Template(VC++)

                                MessageDef.cpp

   =========================================================================== */
#include "stdafx.h"

// Message—p•¶Žš—ñ
#define TTB_HSHELL_ACTIVATESHELLWINDOW_MESSAGE	"TTBase HShell Activate ShellWindow"
#define TTB_HSHELL_GETMINRECT_MESSAGE			"TTBase HShell GetMinRect"
#define TTB_HSHELL_LANGUAGE_MESSAGE				"TTBase HShell Language"
#define TTB_HSHELL_REDRAW_MESSAGE				"TTBase HShell Redraw"
#define TTB_HSHELL_TASKMAN_MESSAGE				"TTBase HShell TaskMan"
#define TTB_HSHELL_WINDOWACTIVATED_MESSAGE		"TTBase HShell WindowActivated"
#define TTB_HSHELL_WINDOWCREATED_MESSAGE		"TTBase HShell WindowCreated"
#define TTB_HSHELL_WINDOWDESTROYED_MESSAGE		"TTBase HShell WindowDestroyed"
#define TTB_HMOUSE_ACTION_MESSAGE				"TTBase HMouse Action"
#define TTB_ICON_NOTIFY_MESSAGE					"TTBase ICON NOTIFY"
#define TTB_LOAD_DATA_FILE_MESSAGE				"TTBase LOAD DATA FILE"
#define TTB_SAVE_DATA_FILE_MESSAGE				"TTBase SAVE DATA FILE"

// Message’è‹`
UINT TTB_HSHELL_ACTIVATESHELLWINDOW;
UINT TTB_HSHELL_GETMINRECT;
UINT TTB_HSHELL_LANGUAGE;
UINT TTB_HSHELL_REDRAW;
UINT TTB_HSHELL_TASKMAN;
UINT TTB_HSHELL_WINDOWACTIVATED;
UINT TTB_HSHELL_WINDOWCREATED;
UINT TTB_HSHELL_WINDOWDESTROYED;
UINT TTB_HMOUSE_ACTION;
UINT TTB_ICON_NOTIFY;
UINT TTB_LOAD_DATA_FILE;
UINT TTB_SAVE_DATA_FILE;

void RegisterMessages(void)
{
	TTB_HSHELL_ACTIVATESHELLWINDOW	= RegisterWindowMessageA(TTB_HSHELL_ACTIVATESHELLWINDOW_MESSAGE);
	TTB_HSHELL_GETMINRECT			= RegisterWindowMessageA(TTB_HSHELL_GETMINRECT_MESSAGE);
	TTB_HSHELL_LANGUAGE				= RegisterWindowMessageA(TTB_HSHELL_LANGUAGE_MESSAGE);
	TTB_HSHELL_REDRAW				= RegisterWindowMessageA(TTB_HSHELL_REDRAW_MESSAGE);
	TTB_HSHELL_TASKMAN				= RegisterWindowMessageA(TTB_HSHELL_TASKMAN_MESSAGE);
	TTB_HSHELL_WINDOWACTIVATED		= RegisterWindowMessageA(TTB_HSHELL_WINDOWACTIVATED_MESSAGE);
	TTB_HSHELL_WINDOWCREATED		= RegisterWindowMessageA(TTB_HSHELL_WINDOWCREATED_MESSAGE);
	TTB_HSHELL_WINDOWDESTROYED		= RegisterWindowMessageA(TTB_HSHELL_WINDOWDESTROYED_MESSAGE);
	TTB_HMOUSE_ACTION				= RegisterWindowMessageA(TTB_HMOUSE_ACTION_MESSAGE);
	TTB_ICON_NOTIFY					= RegisterWindowMessageA(TTB_ICON_NOTIFY_MESSAGE);
	TTB_LOAD_DATA_FILE				= RegisterWindowMessageA(TTB_LOAD_DATA_FILE_MESSAGE);
	TTB_SAVE_DATA_FILE				= RegisterWindowMessageA(TTB_SAVE_DATA_FILE_MESSAGE);
}